# base image
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Copy to working directory
COPY package*.json ./

RUN npm install --force

# Bundle app source
COPY . .

EXPOSE 3001

# Command to run
CMD ["node", "index.js"]
